version: 2.1
jobs:
  run-lint-and-upload-data:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:       
          name: Install Yarn
          command: npm install yarn
      - run: 
          name: Install dependencies
          command: yarn
      - run: 
          name: Run ESLint
          command: yarn lint
      - run:
          name: Create post content from lint result file
          command: node ./scripts/format-content-file.js
      - run: 
          name: Install curl
          command: sudo apt install curl
      - run:
          name: Upload lint result data to server
          command: >-
            curl -d "$(cat postBody.json)" -H 'Content-Type: application/json' -X POST $DATA_SERVICE_URL --http1.1
workflows:
  run-eslint:
    jobs:
      - run-lint-and-upload-data
