version: 2.1
jobs:
  run-sample-pipeline:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: npm install yarn
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run ESLint
          command: yarn lint
      - run:
          name: Create post content from lint result file
          command: node ./scripts/format-content-file.js
      - run:
          name: Call data exporter script
          command: node ./ci/g11n-data-exporter/index.js
workflows:
  run-eslint:
    jobs:
      - run-sample-pipeline
