version: 2.1
jobs:
  run-sample-pipeline:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: npm install yarn
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run ESLint
          command: yarn lint
workflows:
  run-eslint:
    jobs:
      - run-sample-pipeline
